### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by fredguth** [linonetwo/Tiddlywiki-NodeJS-Github-Template#12]
Hi, 
I am not sure if this repo is exactly what I am trying to accomplish.  I want to have a TW node.js wiki that I can autosave at Github.  TW has the GH autosave for html wikis only.

I would like to understand better your project and even collaborate on development.  But I don't speak Chinese. 🤷‍♂️ 

I also tried to use the TiddlyGit desktop app that you are also involved with.  But despite the translations, the connection to Github is in Chinese and I believe there was an error that I could not understand.

Thanks

**Comment by linonetwo** [comment]
@fredguth Hi, I've done 100% English translation in TG note, you can see there is a "Language" in the menu.

<img width="239" alt="Screen Shot 2020-09-08 at 9 28 32 PM" src="https://user-images.githubusercontent.com/3746270/92482486-404bc380-f21a-11ea-8aef-cd390b27fe4c.png">

And surely I will translate this template later, this is an irreplaceable progressive solution for nodejs wiki user (as far as TG note stays in beta).

**Comment by fredguth** [comment]
I got that... eventually. But still, a lot of error messages in Chinese.  But that is ok.

**Comment by linonetwo** [comment]
If you encounter error, you can paste message to pastebin, and open an issue in TG note's repo, I will probably fix it.

"error messages in Chinese" may come from the time before you switch the language.

Log from next day after you switch language will be fine.
