### ISSUE TITLE
使用预览窗格(alt+p)会导致编辑栏错位遮挡内容

### ISSUE THREAD

**Issue by Morxi** [linonetwo/Tiddlywiki-NodeJS-Github-Template#5]
发现作者公开wiki也有这个bug（逃   
自己加了一行css不遮挡了，但是还是不知道怎么让其可以在预览模式下随滑动贴在顶部   
`.tc-tiddler-preview .tc-editor-toolbar 
{
	position: unset;
}`

**Comment by linonetwo** [comment]
这个不好搞的，可能得等上游改成 flex 布局 https://github.com/Jermolene/TiddlyWiki5/issues/4473

我 CSS 不大好，我主要写 JS 的，所以我没法在这方面给他们做出什么贡献。

**Comment by linonetwo** [comment]
我之前是设置了 .tc-editor-toolbar 的 position sticky，之前能用，更新到 5.2.2 之后好像是 HTML 的结构变了，所以就不行了。

sticky 我一直都是瞎试的，至今难以明白其中的奥妙。

我现在也取消掉了工具栏的浮动。

之后搞一个像 notion 那种风格的浮动工具栏吧…

**Comment by linonetwo** [comment]
哈哈 我知道了，今天学了一下 CSS，发现原来父母有 overflow 的时候，就不能 sticky 了，所以现在我修好了。
