### ISSUE TITLE
feature request: Autocompletion of wiki-links

### ISSUE THREAD

**Issue by afenc** [linonetwo/Tiddlywiki-NodeJS-Github-Template#7]
when you type “[[” a pop-up appears providing a tiddle list accordingly
something like this
https://giffmex.org/stroll/stroll.html

**Comment by linonetwo** [comment]
OK, I will see how he achieved this, using what plugin.

**Comment by afenc** [comment]
Thanks for prompt response.
in the same "Stroll" project he also implants an useful feature
"side-by-side editing of multiple notes."
Please check that as well if possible.

**Comment by linonetwo** [comment]
Hi, for autocomplete, I found they are just using http://snowgoon88.github.io/TW5-extendedit/#About%20the%20Edit-CompText%20plugin this plugin, just install it and read the readme of it ( it requires some modification to the config).

**Comment by linonetwo** [comment]
I will release all my modification as a "plugin pack" later, so downstream user of this template repo can always get the latest plugin recommendation.

Currently, old user of this repo is not able to receive update, which is very inconvenient.

**Comment by linonetwo** [comment]
For two column, it is using https://groups.google.com/forum/#!searchin/tiddlywiki/stories$20column|sort:date/tiddlywiki/d60QYKycUCY/Fcn9yB9-AwAJ

I think it is not so mature, experience is not as good as VSCode two coulmn.
